language: node_js
node_js:
  - '8'
  - '10'
before_script:
  - export TZ=Europe/Madrid
script: npm run travis
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
cache:
  yarn: true
